#!/usr/bin/env bash

cd "$(dirname "$(readlink -f "$0")")" || exit
name=$1
if [ -n "$1" ]; then
  file=$(find . -maxdepth 2 -type f \( -name "$name.yml" -o -name "$name.yaml" \) | head -n 1)
  if [ -f "$file" ]; then
    docker compose -f "$file" -p "$name" up -d
  else
    echo "File $name.yml/yaml not found."
    exit 1
  fi
else
  find . -maxdepth 2 -type f \( -name "*.yml" -o -name "*.yaml" \) | while read -r file; do
    name=$(basename "${file%.*}")
    docker compose -f "$file" -p "$name" up -d
  done
fi

start_status=$?
if [[ $start_status -eq 0 ]]; then
  echo "success!"
else
  echo "failure!"
fi
