#!/bin/bash
cd "$(dirname "$(readlink -f "$0")")" || exit
name=$1
if [ -n "$name" ]; then
    if docker ps --format '{{.Names}}' | grep -qw "$name"; then
        file=$(find . -maxdepth 1 -type f \( -name "$name.yml" -o -name "$name.yaml" \) | head -n 1)
        if [ -f "$file" ]; then
            docker compose -f "$file" -p "$name" down
            docker compose -f "$file" -p "$name" up -d
        else
            echo "File $name.yml/yaml not found."
            exit 1
        fi
    else
        echo "Docker container $name not found"
    fi
else
    for file in *.yml *.yaml; do
        [ -f "$file" ] || continue
        name="${file%.*}"
        docker compose -f "$file" -p "$name" down
        docker compose -f "$file" -p "$name" up -d
    done
fi
