#!/usr/bin/env bash

cd "$(dirname "$(readlink -f "$0")")" || exit 1

updateFailed=()
updateSuccess=()

# List of files to ignore (just the filename, not the path)
ignoreFiles=("hwaccel.ml.yml" "hwaccel.transcoding.yml")

isIgnored() {
  local file="$1"
  for ignore in "${ignoreFiles[@]}"; do
    if [[ "$(basename "$file")" == "$ignore" ]]; then
      return 0
    fi
  done
  return 1
}

isRunning() {
  local composeFile="$1"
  local containers
  containers=$(docker compose -f "$composeFile" ps -q)
  if [ -z "$containers" ]; then
    return 1
  fi

  local failed=()
  local running=()

  for container in $containers; do
    local state
    state=$(docker inspect -f '{{.State.Running}}' "$container")
    if [[ "$state" == "true" ]]; then
      running+=("$container")
    else
      failed+=("$container")
    fi
  done

  [[ ${#running[@]} -gt 0 ]] && return 0 || return 1
}

updateImage() {
  local composeFile="$1"

  if isIgnored "$composeFile"; then
    echo "Skipping ignored file: $composeFile"
    return
  fi

  local projectName
  projectName=$(basename "${composeFile%.*}" | tr '.' '_')

  echo "=> Updating $composeFile ..."

  if isRunning "$composeFile"; then
    if docker compose -f "$composeFile" pull &&
      docker compose -f "$composeFile" -p "$projectName" down &&
      docker compose -f "$composeFile" -p "$projectName" up -d; then
      updateSuccess+=("$composeFile")
    else
      updateFailed+=("$composeFile")
    fi
  else
    if docker compose -f "$composeFile" pull &&
      docker compose -f "$composeFile" -p "$projectName" up -d; then
      updateSuccess+=("$composeFile")
    else
      updateFailed+=("$composeFile")
    fi
  fi
}

if [ -n "$1" ]; then
  composeFile=$(find . -maxdepth 2 -type f \( -name "$1.yml" -o -name "$1.yaml" \) | head -n 1)
  if [ -f "$composeFile" ]; then
    updateImage "$composeFile"
  else
    echo -e "\nFile $1.yml/yaml not found."
    exit 1
  fi
else
  while read -r composeFile; do
    updateImage "$composeFile"
    echo
  done < <(find . -maxdepth 2 -type f \( -name "*.yml" -o -name "*.yaml" \))
fi

if [ -n "$1" ]; then
  if ((${#updateSuccess[@]})); then
    echo
    printf ' ✔ Successfully updated %s\n' "${updateSuccess[@]}"
  fi

  if ((${#updateFailed[@]})); then
    echo
    printf ' ✘ Failed to update %s\n' "${updateFailed[@]}"
    exit 2
  else
    exit 0
  fi
else
  echo
  echo "===== SUMMARY ====="

  if ((${#ignoreFiles[@]})); then
    echo
    echo "Ignored Files:"
    printf ' \033[1mℹ\033[0m %s\n' "${ignoreFiles[@]}"
  fi

  if ((${#updateSuccess[@]})); then
    echo
    echo "Successful updates:"
    printf ' ✔ %s\n' "${updateSuccess[@]}"
  fi

  if ((${#updateFailed[@]})); then
    echo
    echo "Failed updates:"
    printf ' ✘ %s\n' "${updateFailed[@]}"
    exit 2
  else
    exit 0
  fi
fi
