#!/usr/bin/env bash

cd "$(dirname "$(readlink -f "$0")")" || exit 1

startSkipped=()
startFailed=()
startSuccess=()

# List of files to ignore (just the filename, not the path)
ignoreFiles=("hwaccel.ml.yml" "hwaccel.transcoding.yml")

isIgnored() {
  local file="$1"
  for ignore in "${ignoreFiles[@]}"; do
    if [[ "$(basename "$file")" == "$ignore" ]]; then
      return 0
    fi
  done
  return 1
}

isRunning() {
  local composeFile="$1"
  local containers
  containers=$(docker compose -f "$composeFile" ps -q)
  if [ -z "$containers" ]; then
    return 1
  fi

  local failed=()
  local running=()

  for container in $containers; do
    local state
    state=$(docker inspect -f '{{.State.Running}}' "$container")
    if [[ "$state" == "true" ]]; then
      running+=("$container")
    else
      failed+=("$container")
    fi
  done

  [[ ${#running[@]} -gt 0 ]] && return 0 || return 1
}

startContainer() {
  local composeFile="$1"

  if isIgnored "$composeFile"; then
    echo "Skipping ignored file: $composeFile"
    return
  fi

  local projectName
  projectName=$(basename "${composeFile%.*}" | tr '.' '_')

  if isRunning "$composeFile"; then
    echo "$projectName is already Running!!!"
    startSkipped+=("$composeFile")
    return
  fi

  echo "=> Starting $composeFile ..."

  if docker compose -f "$composeFile" -p "$projectName" up -d; then
    startSuccess+=("$composeFile")
  else
    startFailed+=("$composeFile")
  fi
}

if [ -n "$1" ]; then
  composeFile=$(find . -maxdepth 2 -type f \( -name "$1.yml" -o -name "$1.yaml" \) | head -n 1)
  if [ -f "$composeFile" ]; then
    startContainer "$composeFile"
  else
    echo -e "\nFile $1.yml/yaml not found."
    exit 1
  fi
else
  while read -r composeFile; do
    startContainer "$composeFile"
    echo
  done < <(find . -maxdepth 2 -type f \( -name "*.yml" -o -name "*.yaml" \))
fi

if [ -n "$1" ]; then
  if ((${#startSkipped[@]})); then
    echo
    printf ' \033[1mℹ\033[0m Skipped (already running) %s\n' "${startSkipped[@]}"
  fi

  if ((${#startSuccess[@]})); then
    echo
    printf ' ✔ Successfully started %s\n' "${startSuccess[@]}"
  fi

  if ((${#startFailed[@]})); then
    echo
    printf ' ✘ Failed to start %s\n' "${startFailed[@]}"
    exit 2
  else
    exit 0
  fi
else
  echo
  echo "===== SUMMARY ====="

  if ((${#ignoreFiles[@]})); then
    echo
    echo "Ignored Files:"
    printf ' \033[1mℹ\033[0m %s\n' "${ignoreFiles[@]}"
  fi

  if ((${#startSkipped[@]})); then
    echo
    echo "Skipped (already running):"
    printf ' \033[1mℹ\033[0m %s\n' "${startSkipped[@]}"
  fi

  if ((${#startSuccess[@]})); then
    echo
    echo "Successful starts:"
    printf ' ✔ %s\n' "${startSuccess[@]}"
  fi

  if ((${#startFailed[@]})); then
    echo
    echo "Failed starts:"
    printf ' ✘ %s\n' "${startFailed[@]}"
    exit 2
  else
    exit 0
  fi
fi
