services:
  valkey:
    container_name: valkey
    image: docker.io/valkey/valkey:latest
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - ./searxng/valkey:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    image: "docker.io/searxng/searxng:latest"
    container_name: searxng
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "8181:8080"
    volumes:
      - ./searxng/config:/etc/searxng:rw
      - ./searxng/data:/var/cache/searxng:rw
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:
