services:
  syncyomi:
    container_name: syncyomi
    image: ghcr.io/syncyomi/syncyomi:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ./syncyomi/config:/config
    ports:
      - 8282:8282
