services:
  syncyomi:
    container_name: syncyomi
    image: ghcr.io/syncyomi/syncyomi:latest
    restart: unless-stopped
    networks:
      - syncyomi
    environment:
      - TZ=${TZ}
    volumes:
      - ./syncyomi/config:/config
    ports:
      - 8282:8282

networks:
  syncyomi: