use_default_settings: true

search:
  autocomplete: "duckduckgo"
  favicon_resolver: "duckduckgo"
  default_lang: "auto"
# Available languages
  # languages:
  #   - all
  #   - en
  #   - en-US
  #   - de
  #   - it-IT
  #   - fr
  #   - fr-BE

server:
  limiter: true
  secret_key: "ultrasecretkey"
  # ^ Is overwritten by ${SEARXNG_SECRET}
  image_proxy: true
  # POST queries are "more secure!" but are also the source of hard-to-locate
  # annoyances, which is why GET may be better for end users and their browsers.
  # see https://github.com/searxng/searxng/pull/3619
  # Is overwritten by ${SEARXNG_METHOD}
  method: "GET"

valkey:
  # URL to connect valkey database. Is overwritten by ${SEARXNG_VALKEY_URL}.
  # https://docs.searxng.org/admin/settings/settings_valkey.html#settings-valkey
  # url: valkey://localhost:6379/0
  url: valkey://valkey:6379/0

ui:
  # Default interface locale - leave blank to detect from browser information or
  # use codes from the 'locales' config section
  default_locale: ""
  # Open result links in a new tab by default
  results_on_new_tab: true
  theme_args:
    # style of simple theme: auto, light, dark
    simple_style: black

outgoing:
  # default timeout in seconds, can be override by engine
  request_timeout: 20.0