services: 
  docktail:
    container_name: docktail
    image: ghcr.io/marvinvr/docktail:latest
    restart: unless-stopped
    volumes:
        - /var/run/tailscale:/var/run/tailscale
        ##Docker
        #- /var/run/docker.sock:/var/run/docker.sock:ro
        ##Podman
        ## root mode
        #- "/run/podman/podman.sock:/var/run/docker.sock"
        ## rootless mode
        - "$XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock"
        #- "/run/user/1000/podman/podman.sock:/var/run/docker.sock"
    environment:
      - TAILSCALE_OAUTH_CLIENT_ID=${TAILSCALE_OAUTH_CLIENT_ID}
      - TAILSCALE_OAUTH_CLIENT_SECRET=${TAILSCALE_OAUTH_CLIENT_SECRET}
      - DEFAULT_SERVICE_TAGS=tag:docktail
      - IGNORE_SERVICE_NAMES=${IGNORE_SERVICE_NAMES} #ignore these service from being deleted/unlisted - mainly useful for services which are not done from docktail
      - DELETE_UNUSED_SERVICES=true
