services:
  vaultwarden:
    container_name: vaultwarden
    image: 'vaultwarden/server:latest'
    restart: unless-stopped
    environment:
     - DOMAIN=${VAULTWARDEN_DOMAIN}
    volumes:
      - ./vaultwarden/vw-data/:/data/
    ports:
      - 81:80
    labels:
      - "docktail.service.enable=true"
      - "docktail.service.name=vaultwarden"
      - "docktail.service.port=80"
      - "docktail.service.service-port=443"
      - "docktail.tags=tag:docktail"
