name: diun

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "./diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=${TZ}"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true" #needed to scan all the images in docker
      #Notification
      ##Mail SMTP
      #- DIUN_NOTIF_MAIL_HOST=${DIUN_NOTIF_MAIL_HOST}
      #- DIUN_NOTIF_MAIL_PORT=${DIUN_NOTIF_MAIL_PORT}
      #- DIUN_NOTIF_MAIL_SSL=${DIUN_NOTIF_MAIL_SSL}
      #- DIUN_NOTIF_MAIL_INSECURESKIPVERIFY=${DIUN_NOTIF_MAIL_INSECURESKIPVERIFY}
      #- DIUN_NOTIF_MAIL_LOCALNAME=${DIUN_NOTIF_MAIL_LOCALNAME}
      #- DIUN_NOTIF_MAIL_USERNAME=${DIUN_NOTIF_MAIL_USERNAME}
      #- DIUN_NOTIF_MAIL_PASSWORD=${DIUN_NOTIF_MAIL_PASSWORD}
      #- DIUN_NOTIF_MAIL_FROM=${DIUN_NOTIF_MAIL_FROM}
      #- DIUN_NOTIF_MAIL_TO=${DIUN_NOTIF_MAIL_TO}
      #- DIUN_NOTIF_MAIL_TEMPLATETITLE=${DIUN_NOTIF_MAIL_TEMPLATETITLE}
      #- DIUN_NOTIF_MAIL_TEMPLATEBODY=${DIUN_NOTIF_MAIL_TEMPLATEBODY}
      #webhook
      - "DIUN_NOTIF_WEBHOOK_ENDPOINT=http://127.0.0.1:9999"
      - "DIUN_NOTIF_WEBHOOK_METHOD=POST"
      #telegram
      - "DIUN_NOTIF_TELEGRAM_TOKEN=${DIUN_NOTIF_TELEGRAM_TOKEN}"
      - "DIUN_NOTIF_TELEGRAM_CHATIDS=${DIUN_NOTIF_TELEGRAM_CHATIDS}"
    labels:
      - "diun.enable=true" # if DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT is not set or false, manually add this label to each container you want to monitor
    restart: always
    network_mode: host #required for webhook to send request on host machine
